In [1]:
from datasets import load_dataset

# KLUE-MRC 데이터셋 불러오기
dataset = load_dataset("klue", "mrc")

README.md:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/21.4M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/8.68M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/17554 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5841 [00:00<?, ? examples/s]

In [ ]:
df_train = dataset['train']

Dataset({
    features: ['title', 'context', 'news_category', 'source', 'guid', 'is_impossible', 'question_type', 'question', 'answers'],
    num_rows: 17554
})

In [5]:
set(df_train['source'])

{'acrofan', 'hankyung', 'wikipedia'}

In [12]:
pd_train = df_train.to_pandas()

In [13]:
subjects = ['경제', '교육산업', '국제', '부동산', '사회', '생활', '책마을']
pd_subjects = pd_train[pd_train['news_category'].isin(subjects)]
pd_subjects

,title,context,news_category,source,guid,is_impossible,question_type,question,answers
1,"부산정보산업진흥원, 과기부 지역SW서비스사업화 지원사업 4개 과제 선정",부산시와 (재)부산정보산업진흥원(원장 이인숙)이 ‘2020~2021년 지역SW서비스...,경제,acrofan,klue-mrc-v1_train_06118,True,3,성공적인 성과를 보인 지역SW서비스사업화 지원사업의 주최자는?,"{'answer_start': [18, 21, 1673], 'text': ['원장 ..."
2,"부산정보산업진흥원, 과기부 지역SW서비스사업화 지원사업 4개 과제 선정",부산시와 (재)부산정보산업진흥원(원장 이인숙)이 ‘2020~2021년 지역SW서비스...,경제,acrofan,klue-mrc-v1_train_14934,False,2,지능형 생산자동화 기반기술을 개발중인 스타트업은?,"{'answer_start': [1422], 'text': ['삼보테크놀로지']}"
14,"코로나 19 심각 단계 격상에 따라 2020 정동극장 레퍼토리 적벽, 3월 8일까지...",(재)정동극장(대표이사 김희철)은 정부가 23일 코로나 19 위기 경보를 ‘심각’ ...,생활,acrofan,klue-mrc-v1_train_10973,False,1,코로나19 심각 단계 선언 전에 계획했던 적벽의 마지막 공연일은?,"{'answer_start': [133], 'text': ['4월 5일']}"
20,강태진·김명환·성낙인·오세정·조동성 … ‘서울대 총장 후보’ 압축 ...“국가정책 ...,서울대 차기 총장직에 나선 총장예비후보자가 5명으로 압축됐다. 서울대 총장추천위원회...,사회,hankyung,klue-mrc-v1_train_16861,False,1,서울대학교 다음 총장으로 출마한 후보 수는?,"{'answer_start': [1040, 1040], 'text': ['12명',..."
35,"위메프 배달앱 ‘위메프오’, 이번엔 “반값 BBQ” 파격 행사",위메프의 배달∙픽업 서비스 위메프오가 23~25일 3일간 ‘BBQ 50% 페이백’ ...,경제,acrofan,klue-mrc-v1_train_16184,True,3,BBQ가 위메프오 입점을 포기했다고 설명한 사람의 이름은?,"{'answer_start': [263], 'text': ['송민주']}"
...,...,...,...,...,...,...,...,...,...
17523,원자 두께‘멤브레인 반도체’세계 최초로 3차원 구현,거북선의 지붕처럼 오돌토돌 정교한 가시가 돋친 새로운 구조의 반도체 소자가 개발됐다...,사회,acrofan,klue-mrc-v1_train_07427,True,3,멤브레인 반도체 개발에 실패한 사람의 이름은?,"{'answer_start': [94], 'text': ['조문호']}"
17529,시선집중! 이 아파트 안성 푸르지오...‘서울세종고속道’ 호재 안성서 2년 만에 분양,대우건설이 18일 경기 안성시에서 처음으로 ‘안성 푸르지오’(759가구) 모델하우스...,부동산,hankyung,klue-mrc-v1_train_14462,True,3,안성 인근의 주택 수요가 부족하다고 한 사람은?,"{'answer_start': [1327, 1336, 1343, 1343], 'te..."
17540,낡은 두 집 합치면 ...재건축 더 쉬워진다,"주차장, 도로사선 등의 규정을 충족할 수 없어 재건축이 힘들었던 낡은 주택을 이웃한...",부동산,hankyung,klue-mrc-v1_train_13454,False,2,3개 필지를 묶어 건축협정을 체결한 사업지는?,"{'answer_start': [639, 639], 'text': ['경북 영주2동..."
17542,다자간협상 연내 재개할 것”,“WTO 협상은 항상 실패했다는 관성을 깨야 합니다. 그래야 최근 타결한 ‘발리 패...,경제,hankyung,klue-mrc-v1_train_10193,False,1,DDA 협상이 결렬된 해는?,"{'answer_start': [450, 450], 'text': ['2008년',..."
17546,정글 같은 비즈니스 세계...성공법칙은 ‘사랑·섬김·보살핌’,뉴욕에서 벤처기업을 운영하는 젊은 사업가 마이클은 어느 날 조깅을 하는 도중 정신을...,책마을,hankyung,klue-mrc-v1_train_11047,False,1,책 '뉴욕 111번가의 목수' 의 주인공 마이클을 병원으로 데려다 준 사람의 직업은?,"{'answer_start': [161], 'text': ['목수']}"

In [14]:
set(pd_subjects['news_category'])

{'경제', '교육산업', '국제', '부동산', '사회', '생활', '책마을'}

In [15]:
pd_subjects.to_csv('kluemrc_subjects.csv')

In [18]:
df_valid = dataset['validation']
pd_valid = df_valid.to_pandas()

In [20]:
subjects = ['경제', '교육산업', '국제', '부동산', '사회', '생활', '책마을']
valid_subjects = pd_valid[pd_valid['news_category'].isin(subjects)]
valid_subjects

,title,context,news_category,source,guid,is_impossible,question_type,question,answers
1,"佛 검찰 “독일 여객기, 부조종사가 의도적으로 추락”",프랑스 남부 알프스에 떨어져 150명의 사망자를 낸 저먼윙스 여객기는 부조종사가 의...,국제,hankyung,klue-mrc-v1_dev_01842,False,1,사고 비행기의 목적지는?,"{'answer_start': [556], 'text': ['독일 뒤셀도르프']}"
2,"도전적인 일, 리더에 대한 신뢰, 협력 문화 …...가고 싶다, 이 회사 … 베인&...",가장 일하고 싶은 회사로 미국 컨설팅 업체인 베인&컴퍼니가 선정됐다. 트위터와 링크...,국제,hankyung,klue-mrc-v1_dev_03566,True,3,퇴사하고 싶은 회사로 트위터가 순위에 선정된 해는?,"{'answer_start': [155, 155], 'text': ['2014년',..."
3,"도전적인 일, 리더에 대한 신뢰, 협력 문화 …...가고 싶다, 이 회사 … 베인&...",가장 일하고 싶은 회사로 미국 컨설팅 업체인 베인&컴퍼니가 선정됐다. 트위터와 링크...,국제,hankyung,klue-mrc-v1_dev_02673,False,2,2014년 일하고 싶은 50대 회사 중에서 5위로 선정된 기업은?,"{'answer_start': [543], 'text': ['페이스북']}"
4,"도전적인 일, 리더에 대한 신뢰, 협력 문화 …...가고 싶다, 이 회사 … 베인&...",가장 일하고 싶은 회사로 미국 컨설팅 업체인 베인&컴퍼니가 선정됐다. 트위터와 링크...,국제,hankyung,klue-mrc-v1_dev_05664,False,1,포브스의 2014년 일하고 싶은 50대 회사 조사에서 5위를 한 기업은?,"{'answer_start': [543], 'text': ['페이스북']}"
7,"국토부-코레일, 용산 공영개발 놓고 ‘신경전’...국토부 “증자 통한 코레일 주도 ...",채무불이행(디폴트) 상태에 빠진 서울 용산 국제업무지구 개발사업(이하 용산 개발사업...,부동산,hankyung,klue-mrc-v1_dev_03749,False,1,코레일이 증자해서 만들고자 하는 자본금 액수는?,"{'answer_start': [731, 1352], 'text': ['5조원', ..."
...,...,...,...,...,...,...,...,...,...
5828,"감각적 욕망, 사랑으로 승화시키기","진실한 사랑은 기쁨과 평화를 낳고 고통을 줄여준다. 그것은 자애, 연민, 기쁨, 평...",책마을,hankyung,klue-mrc-v1_dev_02801,True,3,수행 방법을 통해 사랑을 감각적 욕망으로 승화시키는 내용이 담긴 책은?,"{'answer_start': [260, 261], 'text': ['《틱낫한 스님..."
5834,"SK하이닉스, 국내기업 최초 폐기물 매립 제로(Zero) 인증 획득",SK하이닉스가 국내기업 중 최초이자 세계에서 14번째로 폐기물 매립 제로(Zero ...,사회,acrofan,klue-mrc-v1_dev_05788,False,2,SK하이닉스가 획득한 폐기물 매립 제로 인증 등급은?,"{'answer_start': [102, 102, 106], 'text': ['실버..."
5835,최하위에 A … 유명무실한 ‘음식점 위생등급제’,서울시가 2009년부터 추진한 ‘음식점 위생등급제’가 유명무실하게 운영되고 있는 것...,사회,hankyung,klue-mrc-v1_dev_04659,False,1,음식점이 위생등급을 얻기 위한 최소 점수는?,"{'answer_start': [435, 435], 'text': ['70점', '..."
5839,강남·서초 유치원·초교 8~10일 전면휴업,"서울교육청이 8일부터 10일까지 강남구, 서초구 지역에 있는 유치원, 초등학교의 전...",사회,hankyung,klue-mrc-v1_dev_04183,False,1,강남지역에 사는 학생들은 며칠 동안 학교를 안가나?,"{'answer_start': [313], 'text': ['사흘']}"
5840,"AIIB로 탄력받은 中, EU인프라펀드에 대규모 출자",중국이 유럽연합(EU)이 추진 중인 EU인프라투자펀드에 대규모 자금을 출자한다. 아...,국제,hankyung,klue-mrc-v1_dev_03199,False,1,"로이터통신에 따르면, EU인프라펀드 출자에 대한 중국의 공표가 있을 나라는?","{'answer_start': [158], 'text': ['벨기에']}"